server:
  port: 8083

spring:
  application:
    name: tracker

  datasource:
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5433/postgres?CurrentSchema=tracker"

  jpa:
    hibernate:
      ddl-auto: update